[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "openqudit"
version = "0.1.1"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[tool.cibuildwheel]
build = "cp39-* cp310-* cp311-* cp312-*"
container-engine = "podman"
skip = "*musllinux*"

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux_2_28"
before-all = "dnf install -y llvm-devel-18.1.8-3.module_el8.10.0+3903+ca21d481 libffi-devel ncurses-devel"

[tool.cibuildwheel.macos]
before-all = "echo ${MACOSX_DEPLOYMENT_TARGET} && brew install llvm@18"

[tool.cibuildwheel.macos.environment]
MACOSX_DEPLOYMENT_TARGET = "11"

[tool.cibuildwheel.windows]
archs = ["auto64"]
before-all = "choco install llvm --version=18.1.8 --allow-downgrade"
