[build-system]
requires = ["setuptools", "setuptools-rust", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "openqudit"
version = "0.1.1"

[tool.setuptools]
packages = ["qudit"]

[[tool.setuptools-rust.ext-modules]]
target = "qudit.openqudit" 

