[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
    "-l", "static=unwind",
    "-L", "/usr/local/opt/llvm@18/lib"
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
    "-l", "static=unwind",
    "-L", "/opt/homebrew/opt/llvm@18/lib"
]

