# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
from . import circuit
from . import expressions
from . import instantiation
__all__ = [
    "ParamIndices",
    "ParamIndicesIterator",
    "UnitaryMatrix",
    "circuit",
    "expressions",
    "instantiation",
]

@typing.final
class ParamIndices:
    r"""
    Python wrapper for parameter indices.
    
    This provides parameter index functionality to Python, supporting both
    consecutive (Joint) and disjoint parameter representations.
    """
    @property
    def num_params(self) -> builtins.int:
        r"""
        Returns the number of parameters.
        """
    @property
    def start(self) -> builtins.int:
        r"""
        Returns the starting index (for Joint) or first index (for Disjoint).
        """
    @property
    def is_consecutive(self) -> builtins.bool:
        r"""
        Returns whether the parameters are consecutive.
        """
    @property
    def is_empty(self) -> builtins.bool:
        r"""
        Returns whether the parameter indices are empty.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, indices_or_start: typing.Any, length: typing.Optional[builtins.int] = None) -> ParamIndices:
        r"""
        Creates new parameter indices.
        
        # Arguments
        
        * `indices_or_start` - Either an iterable of parameter indices, or the starting index for a consecutive range
        * `length` - Optional length for consecutive range (only used if `indices_or_start` is an integer)
        
        # Examples
        
        ```python
        # Disjoint parameters
        params1 = ParamIndices([0, 2, 5, 7])
        
        # Consecutive parameters starting at index 10 with length 5
        params2 = ParamIndices(10, 5)  # represents [10, 11, 12, 13, 14]
        ```
        """
    def contains(self, index: builtins.int) -> builtins.bool:
        r"""
        Checks if the parameter indices contain the given index.
        """
    def to_list(self) -> builtins.list[builtins.int]:
        r"""
        Returns all parameter indices as a list.
        """
    def sorted(self) -> ParamIndices:
        r"""
        Returns a sorted copy of these parameter indices.
        """
    def union(self, other: ParamIndices) -> ParamIndices:
        r"""
        Unions with another ParamIndices.
        """
    def intersect(self, other: ParamIndices) -> ParamIndices:
        r"""
        Intersects with another ParamIndices.
        """
    @staticmethod
    def constant() -> ParamIndices:
        r"""
        Creates parameter indices for a constant (no parameters).
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def __len__(self) -> builtins.int: ...
    def __iter__(self) -> ParamIndicesIterator: ...
    def __contains__(self, index: builtins.int) -> builtins.bool: ...

@typing.final
class ParamIndicesIterator:
    def __iter__(self) -> ParamIndicesIterator: ...
    def __next__(self) -> typing.Optional[builtins.int]: ...

@typing.final
class UnitaryMatrix:
    r"""
    Python wrapper for UnitaryMatrix
    """
    def __new__(cls, radices: builtins.int | typing.Sequence[builtins.int], matrix: numpy.typing.NDArray[numpy.complex128]) -> UnitaryMatrix:
        r"""
        Create a new unitary matrix from a numpy array
        """
    def to_array(self) -> numpy.typing.NDArray[numpy.complex128]:
        r"""
        Convert to numpy array
        """

