# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from openqudit import circuit
import typing
__all__ = [
    "DefaultInstantiater",
    "Instantiater",
    "InstantiationResult",
    "InstantiationTarget",
    "NativeInstantiater",
    "SequentialMultiStartInstantiater",
]

class Instantiater:
    def instantiate(self, _circuit: circuit.QuditCircuit, _target: InstantiationTarget, _data: dict) -> InstantiationResult: ...

@typing.final
class InstantiationResult:
    r"""
    Python binding for InstantiationResult using f64 as the real number type.
    
    This provides a concrete instantiation of InstantiationResult for use in Python,
    using f64 for real numbers (corresponding to Complex64 complex scalars).
    """
    @property
    def params(self) -> typing.Optional[builtins.list[builtins.float]]:
        r"""
        The instantiated solution parameters
        """
    @property
    def fun(self) -> typing.Optional[builtins.float]:
        r"""
        Optional function evaluation
        """
    @property
    def status(self) -> builtins.int:
        r"""
        Termination status code
        """
    @property
    def message(self) -> typing.Optional[builtins.str]:
        r"""
        Optional message
        """
    def __new__(cls, params: typing.Optional[typing.Sequence[builtins.float]] = None, fun: typing.Optional[builtins.float] = None, status: builtins.int = 0, message: typing.Optional[builtins.str] = None) -> InstantiationResult:
        r"""
        Creates a new InstantiationResult.
        
        Args:
            params: Optional list of solution parameters
            fun: Optional function evaluation value
            status: Status code (0 for success)
            message: Optional diagnostic message
        
        Returns:
            New InstantiationResult instance
        """
    @staticmethod
    def success(params: typing.Sequence[builtins.float], fun: typing.Optional[builtins.float] = None) -> InstantiationResult:
        r"""
        Creates a successful instantiation result.
        
        Args:
            params: The computed solution parameters
            fun: Optional function evaluation
        
        Returns:
            Successful InstantiationResult
        """
    @staticmethod
    def failure(status: builtins.int, message: typing.Optional[builtins.str] = None) -> InstantiationResult:
        r"""
        Creates a failed instantiation result.
        
        Args:
            status: Error status code (must be > 0)
            message: Optional error message
        
        Returns:
            Failed InstantiationResult
        """
    def is_success(self) -> builtins.bool:
        r"""
        Returns True if the instantiation was successful.
        """
    def is_failure(self) -> builtins.bool:
        r"""
        Returns True if the instantiation failed.
        """
    def has_params(self) -> builtins.bool:
        r"""
        Returns True if the result contains solution parameters.
        """
    def has_function_value(self) -> builtins.bool:
        r"""
        Returns True if the result contains a function evaluation.
        """
    def num_params(self) -> typing.Optional[builtins.int]:
        r"""
        Returns the number of parameters if available.
        """
    def __repr__(self) -> builtins.str:
        r"""
        String representation of the result.
        """
    def __str__(self) -> builtins.str:
        r"""
        String representation of the result.
        """

@typing.final
class InstantiationTarget:
    def __new__(cls, obj: typing.Any) -> InstantiationTarget: ...
    def is_unitary_matrix(self) -> builtins.bool: ...

@typing.final
class NativeInstantiater:
    def instantiate(self, circuit: circuit.QuditCircuit, target: InstantiationTarget, data: typing.Optional[dict] = None) -> InstantiationResult: ...
    def batched_instantiate(self, circuit: circuit.QuditCircuit, targets: typing.Sequence[InstantiationTarget], data: typing.Optional[dict] = None) -> builtins.list[InstantiationResult]: ...

def DefaultInstantiater() -> NativeInstantiater: ...

def SequentialMultiStartInstantiater(num_starts: builtins.int = 8) -> NativeInstantiater: ...

