name: Build Wheels

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15-intel, macos-14]

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Windows wheels
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          # --- 1. Set up LLVM Environment ---
          $LLVM_VERSION = "18.1.8"
          $LLVM_INSTALL_DIR = Join-Path $env:GITHUB_WORKSPACE "llvm-install"
          $LLVM_URL = "https://github.com/llvm/llvm-project/releases/download/llvmorg-$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-pc-windows-msvc.tar.xz"
          $LLVM_ARCHIVE = "llvm.tar.xz"

          Write-Output "Downloading LLVM from $LLVM_URL"
          Invoke-WebRequest -Uri $LLVM_URL -OutFile $LLVM_ARCHIVE

          Write-Output "Extracting to $LLVM_INSTALL_DIR"
          New-Item -ItemType Directory -Path $LLVM_INSTALL_DIR -ErrorAction SilentlyContinue | Out-Null
          & 7z x $LLVM_ARCHIVE -so | & 7z x -si -ttar -o"$LLVM_INSTALL_DIR"

          Write-Output "Finding extracted directory..."
          $LLVM_SUBDIR = (Get-ChildItem -Path $LLVM_INSTALL_DIR -Directory | Select-Object -First 1).FullName

          Write-Output "Setting LLVM_DIR to $LLVM_SUBDIR"
          $env:LLVM_DIR = $LLVM_SUBDIR

          Write-Output "Setting LLVM_SYS_181_PREFIX to $LLVM_SUBDIR"
          $env:LLVM_SYS_181_PREFIX = $LLVM_SUBDIR

          $LLVM_BIN_DIR = Join-Path $LLVM_SUBDIR "bin"
          Write-Output "Adding $LLVM_BIN_DIR to PATH"
          $env:PATH = "$LLVM_BIN_DIR;$env:PATH"

          Write-Output "Verifying clang version..."
          & clang --version

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.1
        with:
          package-dir: qudit-python

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
