name: Build Wheels

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15-intel, macos-14]

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install LLVM
        if: contains(matrix.os, 'windows')
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1.8"
          directory: ${{ runner.temp }}/llvm

      - name: Set LLVM_SYS_181_PREFIX Environment Variable
        if: contains(matrix.os, 'windows')
        run: echo "LLVM_SYS_181_PREFIX=${{ runner.temp }}\llvm" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.1
        with:
          package-dir: qudit-python

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
